import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = process.cwd();
const LOCAL_ENV_PATH = path.join(ROOT, '.env.local');
const LOCAL_OVERRIDE_PATH = path.join(ROOT, '.env.local.override');
const EXAMPLE_ENV_PATH = path.join(ROOT, '.env.example');

const ENV_SECTIONS = [
  {
    title: 'Supabase Auth',
    entries: [
      { key: 'NEXT_PUBLIC_SUPABASE_URL', example: 'https://your-project-ref.supabase.co' },
      { key: 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY', example: 'sb_publishable_...' },
      {
        key: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
        example: '',
        comment: 'Optional fallback for older projects still using anon keys.',
      },
      { key: 'SUPABASE_SERVICE_ROLE_KEY', example: 'sb_secret_...' },
    ],
  },
  {
    title: 'App URLs',
    entries: [
      {
        key: 'NEXT_PUBLIC_BASE_URL',
        example: 'https://your-domain.vercel.app',
        comment: 'Optional canonical URL override. Route handlers derive the current origin automatically.',
      },
    ],
  },
  {
    title: 'Notifications',
    entries: [
      { key: 'TELEGRAM_BOT_TOKEN', example: '' },
      {
        key: 'TELEGRAM_CHAT_ID',
        example: '',
        comment: 'For private groups, prefer numeric chat ids such as -1001234567890.',
      },
    ],
  },
  {
    title: 'Alert Thresholds',
    entries: [
      { key: 'ALERT_EDGE_MIN', example: '0.05' },
      { key: 'ALERT_COOLDOWN_MS', example: '1800000' },
    ],
  },
  {
    title: 'Data Sources',
    entries: [
      { key: 'POLYMARKET_API_BASE', example: '' },
      { key: 'OPINION_API_BASE', example: '' },
      { key: 'OPINION_API_KEY', example: '' },
      { key: 'KALSHI_API_BASE', example: '' },
      { key: 'PROBO_API_BASE', example: '' },
      { key: 'PREDICTFUN_API_BASE', example: '' },
      { key: 'PREDICTFUN_API_KEY', example: '' },
      { key: 'LIMITLESS_API_BASE', example: '' },
      { key: 'LIMITLESS_API_KEY', example: '' },
    ],
  },
  {
    title: 'Persistence',
    entries: [{ key: 'DATABASE_URL', example: '"file:./dev.db"' }],
  },
  {
    title: 'Stripe',
    entries: [
      { key: 'STRIPE_SECRET_KEY', example: '' },
      { key: 'STRIPE_PRICE_PRO_WEEKLY', example: '' },
      { key: 'STRIPE_PRICE_PRO_MONTHLY', example: '' },
      { key: 'STRIPE_PRICE_PRO_ANNUAL', example: '' },
      { key: 'STRIPE_WEBHOOK_SECRET', example: '' },
    ],
  },
  {
    title: 'Twitter/X',
    entries: [
      { key: 'TWITTER_API_KEY', example: '' },
      { key: 'TWITTER_API_SECRET', example: '' },
      { key: 'TWITTER_ACCESS_TOKEN', example: '' },
      { key: 'TWITTER_ACCESS_TOKEN_SECRET', example: '' },
    ],
  },
];

const KNOWN_KEYS = new Set(
  ENV_SECTIONS.flatMap((section) => section.entries.map((entry) => entry.key)),
);
const RUNTIME_MANAGED_PREFIXES = ['NX_', 'TURBO_', 'VERCEL_'];

function shouldSyncKey(key) {
  if (key === 'VERCEL') return false;
  return !RUNTIME_MANAGED_PREFIXES.some((prefix) => key.startsWith(prefix));
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return { values: new Map() };
  }

  const values = new Map();
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const candidate = trimmed.startsWith('export ') ? trimmed.slice(7) : line;
    const separatorIndex = candidate.indexOf('=');
    if (separatorIndex <= 0) continue;

    const key = candidate.slice(0, separatorIndex).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;

    values.set(key, candidate.slice(separatorIndex + 1));
  }

  return { values };
}

function renderExampleEnv() {
  const lines = [
    '# ArbiFlow environment',
    '# Generated by `npm run env:example`.',
    '# Local development should mirror Vercel production via `npm run env:sync`.',
    '# Add deliberate local-only differences in `.env.local.override`.',
    '',
  ];

  for (const section of ENV_SECTIONS) {
    lines.push(`# ${section.title}`);

    for (const entry of section.entries) {
      if (entry.comment) lines.push(`# ${entry.comment}`);
      lines.push(`${entry.key}=${entry.example}`);
    }

    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderLocalEnv(values, overrideKeys) {
  const lines = [
    '# Generated by `npm run env:sync`.',
    '# Source of truth: Vercel production environment.',
    '# Add deliberate local-only differences in `.env.local.override`.',
    '',
  ];

  for (const section of ENV_SECTIONS) {
    const sectionEntries = section.entries.filter((entry) => values.has(entry.key));
    if (!sectionEntries.length) continue;

    lines.push(`# ${section.title}`);

    for (const entry of sectionEntries) {
      if (overrideKeys.has(entry.key)) {
        lines.push(`# Local override applied for ${entry.key}`);
      }
      lines.push(`${entry.key}=${values.get(entry.key)}`);
    }

    lines.push('');
  }

  const extraKeys = [...values.keys()]
    .filter((key) => !KNOWN_KEYS.has(key))
    .sort((left, right) => left.localeCompare(right));

  if (extraKeys.length) {
    lines.push('# Additional Vercel Environment Variables');

    for (const key of extraKeys) {
      if (overrideKeys.has(key)) {
        lines.push(`# Local override applied for ${key}`);
      }
      lines.push(`${key}=${values.get(key)}`);
    }

    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function pullProductionEnv(tempFilePath) {
  return spawnSync(
    'vercel',
    ['env', 'pull', tempFilePath, '--environment=production', '--yes'],
    {
      cwd: ROOT,
      encoding: 'utf8',
      shell: process.platform === 'win32',
      stdio: 'pipe',
    },
  );
}

function syncLocalEnv() {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'arbiflow-env-'));
  const tempFilePath = path.join(tempDir, '.env.production.pull');

  try {
    const result = pullProductionEnv(tempFilePath);

    if (result.status !== 0 || !fs.existsSync(tempFilePath)) {
      if (fs.existsSync(LOCAL_ENV_PATH)) {
        console.warn('Could not refresh from Vercel production. Keeping the existing .env.local.');
        if (result.stdout?.trim()) console.warn(result.stdout.trim());
        if (result.stderr?.trim()) console.warn(result.stderr.trim());
        return;
      }

      console.error('Could not pull Vercel production environment and no .env.local exists yet.');
      if (result.stdout?.trim()) console.error(result.stdout.trim());
      if (result.stderr?.trim()) console.error(result.stderr.trim());
      process.exit(result.status || 1);
    }

    const productionEnv = parseEnvFile(tempFilePath);
    const localOverrides = parseEnvFile(LOCAL_OVERRIDE_PATH);
    const productionValues = [...productionEnv.values.entries()].filter(([key]) => shouldSyncKey(key));
    const finalValues = new Map(productionValues);

    for (const [key, value] of localOverrides.values.entries()) {
      if (!shouldSyncKey(key)) continue;
      finalValues.set(key, value);
    }

    const overrideKeys = new Set(
      [...localOverrides.values.keys()].filter((key) => shouldSyncKey(key)),
    );

    fs.writeFileSync(
      LOCAL_ENV_PATH,
      renderLocalEnv(finalValues, overrideKeys),
      'utf8',
    );

    const syncedCount = productionValues.length;
    const overrideCount = overrideKeys.size;
    const suffix = overrideCount ? ` with ${overrideCount} local override(s)` : '';
    console.log(`Synced .env.local from Vercel production (${syncedCount} key(s)${suffix}).`);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

function writeExampleEnv() {
  fs.writeFileSync(EXAMPLE_ENV_PATH, renderExampleEnv(), 'utf8');
  console.log('Updated .env.example from the shared environment manifest.');
}

const command = process.argv[2];

if (command === 'sync-local') {
  syncLocalEnv();
} else if (command === 'write-example') {
  writeExampleEnv();
} else {
  console.error('Usage: node scripts/env-manager.mjs <sync-local|write-example>');
  process.exit(1);
}
